eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  datasource:
    name: order-datasource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_sell?useUnicode=true&allowMultiQueries=true&useSSL=false
    username: root
    password: fxl421125
  jpa:
    show-sql: true